### ISSUE TITLE
Install hangs on Setting Up the Package Cache ...

### ISSUE THREAD

**Issue by kurt-rhee** [deto/Miniconda-Install#6]
I am attempting to install Miniconda 3 4.8.2, but the install hangs on setting up the package cache ... and does not progress no matter how long I leave it there.

I am installing on Windows 10 and running the install as an administrator.  Please let me know what other information you might need.

Thank you in advance for your help.

![image](https://user-images.githubusercontent.com/33131958/77610774-e01dcb00-6ee0-11ea-9031-70aba347372a.png)

**Comment by deto** [comment]
Hi Kurt - I suspect you're just trying to install Miniconda from Continuum.  This isn't an official repo for them - it's just a project I made (many years ago) that used Miniconda to install a bundled python app.  I would see if you could find help on https://www.anaconda.com/
